import 'dart:io';
import 'package:flutter/material.dart';

class Global{
  static String? name;
  static String? email;
  static int? number;
  static String? address;
  static File? file;
  static String? des;
  static String? exp;
  static String? birth;
  static String? group;
  static bool english = false;
  static bool hindi = false;
  static bool gujarati = false;
  static List myLanguage = [];
  static String? nation;
  static String? course;
  static String? college;
  static String? percentage;
  static String? year;
  static String? ref;
  static String? designation;
  static String? institute;
  static String? company;
  static String? school;
  static String? role;
  static String? status;
  static bool enable = false;
  static Color myColor1 = Colors.grey.shade500;
  static Color myColor2 = Colors.black;
  static String? start;
  static String? end;
  static String? project;
  static bool cLanguage = false;
  static bool c = false;
  static bool flutter = false;
  static List technologies = [];
  static String? roles;
  static String? tech;
  static String? description;
  static String? desc;
  static String? date;
  static String? place;
  static bool isTrue = false;
  static String? skill;
  static List skills = [];
  static String? interest;
  static List achievements = [];
}